CREATE TABLE public.training_plan_day (
  ID                BIGSERIAL PRIMARY KEY,
  TRAINING_PLAN_ID  BIGINT NOT NULL,
  TITLE             TEXT NOT NULL,
  CONSTRAINT FK_TRAINING_PLAN_DAY_TRAINING_PLAN FOREIGN KEY (TRAINING_PLAN_ID) REFERENCES public.training_plan_day
);